### ISSUE TITLE
JSON in message field is no parsed

### ISSUE THREAD

**Issue by michael-aldridge** [logzio/logzio-k8s#11]
Kibana just shows the message fields as a JSON blob instead of pulling out each of the fields. Think this is an issue related to this.

See https://github.com/fluent/fluentd/issues/2021

**Comment by idohalevi** [comment]
@michael-aldridge 
Can you please share a sample of the log the is not parsed?

**Comment by michael-aldridge** [comment]
In my (node.js) app if I run
```
console.log(JSON.stringify({event: 'starting request', thing: 'other'}));
```
I get this as part of my kibana log (viewing the log using the JSON tab)
```
 "message": "{\"event\":\"starting request\",\"thing\":\"other\"}\n",
```

**Comment by idohalevi** [comment]
@michael-aldridge 
I'll take a look.

**Comment by bdashrad** [comment]
We had the same issue. One problem we ran into is that some of the docker logs are in json format and some are not, and trying to deal with this conditionally in fluentd was problematic. We ended up not parsing the json on the fluentd side and having logz.io parse it conditionally after shipping.

**Comment by bdashrad** [comment]
It's because of [this change](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/128) made to fluent-plugin-kubernetes_metadata_filter, where they stopped parsing nested json.

**Comment by idohalevi** [comment]
@bdashrad @michael-aldridge 
I read the thread you both mentioned. For now, we will keep parsing it on our (Logz.io) side - contact support.
If you feel in any way you prefer otherwise let me know or send a PR here with the solution.

**Comment by bahtou** [comment]
@michael-aldridge what was the solution for you?
