### ISSUE TITLE
Fluentbit support

### ISSUE THREAD

**Issue by jakubknejzlik** [logzio/logzio-k8s#17]
Hi, does anyone considered using fluentbit instead of fluentd? As far as I know it shouldn't hard to migrate configs to fluent bit and lower memory footprint would be worth it.
Any thoughts or suggestions? :)

**Comment by idohalevi** [comment]
@jakubknejzlik 
Thank you for the suggestion. If you want I would love to work on it together with you as I'm not an expert in FluentBit. Do you know what is the memory diff between them two on avg.?

**Comment by idohalevi** [comment]
Closing this for now
