### ISSUE TITLE
Container crash (CrashLoopBackOff)

### ISSUE THREAD

**Issue by collimarco** [logzio/logzio-k8s#19]
I am using this example:
https://github.com/logzio/logzio-k8s/blob/master/logzio-daemonset.yaml

I have replaced my credentials in the example (token, url).

However the container crashes immediately and the pod status (for all logzio pods) is `CrashLoopBackOff`.

These are the events for a crashing pod:

```
$ kubectl describe pod fluentd-logzio-abcd123 -n kube-system 

Events:
  Type     Reason     Age                    From                  Message
  ----     ------     ----                   ----                  -------
  Normal   Scheduled  4m14s                  default-scheduler     Successfully assigned kube-system/fluentd-logzio-tnm6x to pool-1-x7q3
  Normal   Pulled     3m21s (x4 over 4m11s)  kubelet, pool-1-x7q3  Successfully pulled image "logzio/logzio-k8s:latest"
  Normal   Created    3m21s (x4 over 4m11s)  kubelet, pool-1-x7q3  Created container fluentd
  Normal   Started    3m21s (x4 over 4m11s)  kubelet, pool-1-x7q3  Started container fluentd
  Warning  BackOff    2m44s (x8 over 4m7s)   kubelet, pool-1-x7q3  Back-off restarting failed container
  Normal   Pulling    2m33s (x5 over 4m13s)  kubelet, pool-1-x7q3  Pulling image "logzio/logzio-k8s:latest"
```

Also there aren't any interesting logs to debug the crash:

```
 $ kubectl logs -l k8s-app=fluentd-logzio  -n kube-system 

2019-06-10 14:31:13 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
```

This seems a bug with your image.

Testing on Kubernetes v1.14.1

**Comment by collimarco** [comment]
Note: for testing I am using a new DigitalOcean K8s cluster

**Comment by schwin007** [comment]
@collimarco according to Digital Ocean's documentation RBAC is enabled in their K8S clusters by default.

https://www.digitalocean.com/docs/kubernetes/overview/

Please try to run the daemonset with RBAC and let us know the results. 

https://github.com/logzio/logzio-k8s/blob/master/logzio-daemonset-rbc.yaml

**Comment by collimarco** [comment]
@schwin007 Thank you, the RBAC version works properly!
