### ISSUE TITLE
daemon.extensions wont create 

### ISSUE THREAD

**Issue by dhodyrahmad** [logzio/logzio-k8s#34]
**serviceaccount/fluentd created
clusterrole.rbac.authorization.k8s.io/fluentd created
clusterrolebinding.rbac.authorization.k8s.io/fluentd created
The DaemonSet "fluentd-logzio" is invalid: spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.key: Invalid value: "https://listener.logz.io:8071": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')**

I create the YAML file using kubectl and this happened. did i missed something?

**Comment by yyyogev** [comment]
@dhodyrahmad sorry for the delayed response. The listener host secret shouldn't contain the `https://` prefix and the `:8071` suffix. Only `listener.logz.io` (if you are in the US. See [Account Region](https://docs.logz.io/user-guide/accounts/account-region.html#regions-and-urls) for more info)
