### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by tomasr** [logzio/logzio-k8s#4]
Are you supposed to build and use your own docker image for this?

Notice that the sample yaml templates reference image `logzio/logzio-k8s:1.0.0` which doesn't exist in docker hub, at least.

Or are these published somewhere else?

**Comment by idohalevi** [comment]
@tomasr 
Hi, the image is under logzio in the hub. I tried to pull locally `docker pull logzio/logzio-k8s:1.0.0` and it worked. Do you see any error?

**Comment by tomasr** [comment]
Thanks, @idohalevi. Must have been some network fluke on my end.

It still doesn't seem to be working for me, though. While applying the yaml configuration file works, and creates the daemonset, no pods are scheduled to do any work for it....

**Comment by idohalevi** [comment]
@tomasr 
Do you see some kind of error? which yaml configuration are you using?

**Comment by tomasr** [comment]
Ugh, never mind; apparently this is just me being an idiot. Had two different yaml files that were getting crossed and ended up looking stuff in the wrong namespace. Seems to be working.
