### ISSUE TITLE
Dockerhub environment description seems to be outdated

### ISSUE THREAD

**Issue by amnk** [logzio/logzio-k8s#40]
Guys, description on https://hub.docker.com/r/logzio/logzio-k8s/ has wrong environment variables in the description.

Is that something you could fix?

**Comment by yyyogev** [comment]
@amnk it's fixed, thanks!

**Comment by yyyogev** [comment]
@amnk LOGZIO_LOG_LISTENER and LOGZIO_LOG_SHIPPING_TOKEN are secrets you should set, not env variables. Anyway, it wasn't updated at all, now it's really fixed :)

**Comment by amnk** [comment]
@yyyogev yep, I see it now. Thanks for quick reply and quick fix!
