### ISSUE TITLE
FR: exclude/only include logs from certain k8s namespaces

### ISSUE THREAD

**Issue by lx223** [logzio/logzio-k8s#45]
Hi again, is it possible to add support to customise exclusion or inclusion of logs from certain k8s namespaces? Currently there are a lot of irrelevant logs from namespaces like kube-system and from the fluentd container with messages like:

```
2020-02-16 17:34:52 +0000 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead
```

**Comment by yyyogev** [comment]
We will update our match method as suggested soon.
In the meantime, you could use our [Drop Filters](https://docs.logz.io/user-guide/accounts/drop-filters/) to overcome this

**Comment by lx223** [comment]
Thanks @yyyogev. Will try the filters.

**Comment by lx223** [comment]
Actually, let me keep this open so that I get notification about the release of the namespace filtering.

**Comment by lx223** [comment]
It turns out our account doesn't support drop filters. So will be waiting for the namespace filtering feature for testing. @yyyogev, do you have a rough estimate when that feature is going to land?

**Comment by yyyogev** [comment]
@lx223 this currently has very low priority so no ETA. However, we welcome any contribution from the community

**Comment by eligne-pro** [comment]
Definitely having a way to specify a kubernetes selector on namespaces and labels would be of very high interest for me too, as we are using logzio for some of oour pods only (which are all tagged with some specific labels).

**Comment by mirii1994** [comment]
Hi @lx223 ,
As of version 1.1.5 we added the option to include only certain namespace.

**Comment by Solisol** [comment]
Hi!
We're looking at splitting our production logs and our staging logs to different subaccounts and want to run two daemonsets in our GKE cluster to send the logs. We're experimenting with a setup where we're running 1.1.3 for our old daemonset that scrapes all namespaces, and a new daemonset with version 1.1.5 and 
```yaml
        - name: INCLUDE_NAMESPACE
          value: 'kubernetes.var.log.containers.dev'
```
But we're not seeing this working, as no logs are sent to the new subaccount. (We know the setup works, because before we upgraded the image tag we got ALL THE LOGS to the new subaccount). Any ideas on how we can debug the namespace filtering?

**Comment by mirii1994** [comment]
Hi @Solisol ! If the namespace you want to include is `dev`, can you please try insert this as value: `kubernetes.var.log.containers.**_dev_**` and let us know if this solves the issue?

**Comment by Solisol** [comment]
@mirii1994 Hey! That works great, thank you! 
We were looking at https://app-eu.logz.io/#/dashboard/data-sources/Kubernetes, where the markdown read `**<NAMESPACE>**` as **\<NAMESPACE\>**, so I can see where it went wrong there :D 
Thanks for the quick help!

**Comment by mirii1994** [comment]
@Solisol  glad that it worked out for you, and thanks for letting us know! We'll fix that typo ASAP 🙂

**Comment by mirii1994** [comment]
Hi all,
As of now, you can configure Fluentd via configmap file (update in PR #63), to match it to your needs :)
