### ISSUE TITLE
The DaemonSet "fluentd-logzio" is invalid

### ISSUE THREAD

**Issue by jbdacruz** [logzio/logzio-k8s#49]
I get the following error when trying to run the following command for my eks cluster:

$ kubectl create secret generic logzio-logs-secret --from-literal=logzio-log-shipping-token='<MYTOKEN>' --from-literal=logzio-log-listener='listener-eu.logz.io'  -n kube-system

$ kubectl apply -f https://raw.githubusercontent.com/logzio/logzio-k8s/master/logzio-daemonset-rbac.yaml

The DaemonSet "fluentd-logzio" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"fluentd-logzio", "version":"v1"}: `selector` does not match template `labels`

**Comment by yyyogev** [comment]
Fixed
