### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by bjornmagnusson** [logzio/logzio-k8s#50]
Please consider supporting ARM servers.
Me, and many others are using ARM for easy-to-use Kubernetes clusters

From running the daemonset on ARM cluster:
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by yyyogev** [comment]
Currently, there is no FluentD build for ARM. Since we collect logs through FluentD, we can't support it for now.

**Comment by edwindevaan** [comment]
Please consider supporting arm64

**Comment by mirii1994** [comment]
We now support ARM arch (as of `logzio/logzio-fluentd:1.0.2`)
