### ISSUE TITLE
token is still visible in the output

### ISSUE THREAD

**Issue by pete911** [logzio/logzio-k8s#54]
Even after this commit - https://github.com/logzio/logzio-k8s/commit/f335872e6d8177152df40172c062ce52ab25734d
token is still visible in the output. This is most likely because record_modifier filter (replace log key with message key) is done after. The best would be to move the config from `conf/system.conf` to `conf/fluent.conf`.

**Comment by pete911** [comment]
@mirii1994 @yyyogev not sure if you are the right people, but could you have a look the pull request that is addressing this issue?

**Comment by mirii1994** [comment]
Hi @pete911 , thank you for your contribution!
We're working on our next release, which will disable the sending of Fluentd logs, so we won't need that regex.

**Comment by mirii1994** [comment]
As of version 1.1.5, we configured fluentd to ignore its own logs.
Thanks!
