### ISSUE TITLE
Systemd::JournalError: No such file or directory retrying in 1s

### ISSUE THREAD

**Issue by belapie** [logzio/logzio-k8s#6]
Using the RBAC DaemonSet (https://app.logz.io/#/dashboard/data-sources/Kubernetes) for Kubernetes (1.12.3), systemd constantly spam with : 

> [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s
> [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s
> [in_systemd_kubelet] Systemd::JournalError: No such file or directory retrying in 1s
> [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s

This seems to be related to : https://github.com/fluent/fluentd-kubernetes-daemonset/issues/203
Is there a way to fix this?

**Comment by idohalevi** [comment]
@belapie 
What is your environment?

**Comment by idohalevi** [comment]
@belapie Are you running on Mac, Linux..?

**Comment by belapie** [comment]
@idohalevi Linux Debian 9, all nodes are the sames OS.

> 
> Kernel Version: 4.9.0-8-amd64
> OS Image: Debian GNU/Linux 9 (stretch)
> Container Runtime Version: docker://18.9.0
> Kubelet Version: v1.12.3
> Kube-Proxy Version: v1.12.3

**Comment by jclarksnps** [comment]
@idohalevi are you going to bump the image in docker hub with this?  will this warning do any harm?

**Comment by idohalevi** [comment]
@jclarksnps 
Not sure yet, I feel like giving the user the max coverage of log sources is the best way to approach it. If users need less information they can always modify it.

**Comment by idohalevi** [comment]
@jclarksnps 
You can now disable systemd using variable environment.
See documentation

**Comment by eskuai** [comment]
fluentd
Image:
fluent/fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch
Environment variables:
FLUENT_ELASTICSEARCH_HOST: elasticsearch-logging
FLUENT_ELASTICSEARCH_PORT: 9200
FLUENT_ELASTICSEARCH_SCHEME: http
FLUENT_ELASTICSEARCH_USER: elastic
FLUENT_ELASTICSEARCH_PASSWORD: changeme
FLUENT_UID: 0
FLUENTD_SYSTEMD_CONF: disable
FLUENT_ELASTICSEARCH_SED_DISABLE: true
TZ: Europe/Madrid
Commands:

I got the same problema
 [in_systemd_bootkube] Systemd::JournalError: No such file

**Comment by idohalevi** [comment]
@belapie 
Do you use our image or elasticsearch image?

**Comment by eskuai** [comment]
fluent/fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch

**Comment by eskuai** [comment]
and fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch not working

**Comment by eskuai** [comment]
so sorry, i think i was in fluentd git
sorry

**Comment by idohalevi** [comment]
@eskuai 
All good. If you'll have questions for our image please feel free
