### ISSUE TITLE
ooom killed ruby2.3 process on instances where fluentd is running.

### ISSUE THREAD

**Issue by Saggi432** [logzio/logzio-k8s#8]
we have been facing the below errors when we run the fluentd on our cluster.. apparently getting killed with oom 

on researching it looks like may have to include jmalloc as part of the ruby base image.. can you please confirm if you have any other proposed solutions instead ?

https://github.com/fluent/fluent-bit-kubernetes-logging/issues/14

> 391524.805414] Memory cgroup out of memory: Kill process 3685518 (ruby2.3) score 1792 or sacrifice child
> [468138.916915] Memory cgroup out of memory: Kill process 859933 (ruby2.3) score 1792 or sacrifice child
> [647901.248286] Memory cgroup out of memory: Kill process 2442358 (ruby2.3) score 1792 or sacrifice child
> [675732.117926] IPv6: ADDRCONF(NETDEV_UP): vethb0d99b50: link is not ready
> [729039.765037] [371792]     0 371792   164959    39926     266       4        0           994 ruby2.3
> [729039.774334] Memory cgroup out of memory: Kill process 371792 (ruby2.3) score 1775 or sacrifice child
> [729039.783915] Killed process 371792 (ruby2.3) total-vm:659836kB, anon-rss:149212kB, file-rss:10492kB, shmem-rss:0kB
> [729039.821620] oom_reaper: reaped process 371792 (ruby2.3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
> [853128.254617] Memory cgroup out of memory: Kill process 2316873 (ruby2.3) score 1792 or sacrifice child
> [953790.700466] Memory cgroup out of memory: Kill process 3246659 (ruby2.3) score 1792 or sacrifice child`

**Comment by idohalevi** [comment]
@Saggi432 
Where you able to solve the issue? We never had this issue before

**Comment by bdashrad** [comment]
Try raising the memory requests and limits in your deployment. The lines here can be changed https://github.com/logzio/logzio-k8s/blob/master/logzio-daemonset.yaml#L29-L34

**Comment by idohalevi** [comment]
@bdashrad 
Great feedback!! thank you for the reply
